# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.CharField(max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='lab',
            name='slug',
            field=models.CharField(max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
